<?xml version="1.0" encoding="UTF-8"?>
<!-- Licensed to the Apache Software Foundation (ASF) under the Apache License, Version 2.0. -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.beanshell</groupId>
    <artifactId>bsh-project</artifactId>
    <version>3.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>bsh</artifactId>
  <name>BeanShell Core</name>
  <properties>
    <checkstyle.skip>false</checkstyle.skip>
  </properties>
  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
      </resource>
      <resource>
        <directory>src/conf</directory>
        <targetPath>bsh</targetPath>
        <filtering>true</filtering>
        <includes>
          <include>version.properties</include>
        </includes>
      </resource>
      <resource>
        <directory>..</directory>
        <targetPath>META-INF</targetPath>
        <includes>
          <include>LICENSE</include>
          <include>NOTICE</include>
        </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>biz.aQute.bnd</groupId>
        <artifactId>bnd-maven-plugin</artifactId>
        <configuration>
          <bnd><![CDATA[
Bundle-Version: ${replace;${project.version};-;.}
Bundle-SymbolicName: org.beanshell.bsh
Export-Package: bsh,bsh.classpath,bsh.commands,bsh.engine,bsh.util,bsh.spi,bsh.security,bsh.org.objectweb.asm,bsh.org.objectweb.asm.signature
-includeresource: META-INF/LICENSE=../LICENSE,META-INF/NOTICE=../NOTICE
Main-Class: bsh.Interpreter
Require-Capability: osgi.extender;filter:="(&(osgi.extender=osgi.serviceloader.processor)(version>=1.0.0)(!(version>=2.0.0)))";resolution:=optional,\
 osgi.extender;filter:="(&(osgi.extender=osgi.serviceloader.registrar)(version>=1.0.0)(!(version>=2.0.0)))";resolution:=optional,\
 osgi.serviceloader;filter:="(osgi.serviceloader=bsh.spi.CommandProvider)";cardinality:=multiple;resolution:=optional
Provide-Capability: osgi.serviceloader;osgi.serviceloader=javax.script.ScriptEngineFactory;register:="bsh.engine.BshScriptEngineFactory";uses:="javax.script"
]]></bnd>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.helger.maven</groupId>
        <artifactId>ph-javacc-maven-plugin</artifactId>
        <version>5.0.2</version>
        <executions>
          <execution>
            <id>javacc</id>
            <goals>
              <goal>jjtree-javacc</goal>
            </goals>
            <configuration>
              <jdkVersion>${version.jdk}</jdkVersion>
              <javadocFriendlyComments>true</javadocFriendlyComments>
              <static>false</static>
              <usercharstream>true</usercharstream>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <id>test-helpers</id>
            <goals>
              <goal>test-jar</goal>
            </goals>
            <configuration>
              <includes>
                <include>bsh/TestUtil*.class</include>
                <include>bsh/TestFilter*.class</include>
                <include>bsh/FilteredTestRunner*.class</include>
              </includes>
              <archive combine.self="override"/>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
