/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package bsh;

public interface ParserConstants {

  int EOF = 0;
  int NONPRINTABLE = 6;
  int SINGLE_LINE_COMMENT = 7;
  int HASH_BANG_COMMENT = 8;
  int MULTI_LINE_COMMENT = 9;
  int ABSTRACT = 10;
  int BOOLEAN = 11;
  int BREAK = 12;
  int CLASS = 13;
  int BYTE = 14;
  int CASE = 15;
  int CATCH = 16;
  int CHAR = 17;
  int CONST = 18;
  int CONTINUE = 19;
  int _DEFAULT = 20;
  int DO = 21;
  int DOUBLE = 22;
  int ELSE = 23;
  int FALSE = 24;
  int FINAL = 25;
  int FINALLY = 26;
  int FLOAT = 27;
  int FOR = 28;
  int GOTO = 29;
  int IF = 30;
  int IMPORT = 31;
  int INSTANCEOF = 32;
  int INT = 33;
  int INTERFACE = 34;
  int LONG = 35;
  int NATIVE = 36;
  int NEW = 37;
  int NULL = 38;
  int PRIVATE = 39;
  int PROTECTED = 40;
  int PUBLIC = 41;
  int RETURN = 42;
  int SHORT = 43;
  int STATIC = 44;
  int SWITCH = 45;
  int SYNCHRONIZED = 46;
  int TRANSIENT = 47;
  int THROW = 48;
  int THROWS = 49;
  int TRUE = 50;
  int TRY = 51;
  int VOID = 52;
  int VOLATILE = 53;
  int WHILE = 54;
  int INTEGER_LITERAL = 55;
  int DECIMAL_LITERAL = 56;
  int HEX_LITERAL = 57;
  int OCTAL_LITERAL = 58;
  int FLOATING_POINT_LITERAL = 59;
  int EXPONENT = 60;
  int CHARACTER_LITERAL = 61;
  int STRING_LITERAL = 62;
  int FORMAL_COMMENT = 63;
  int IDENTIFIER = 64;
  int LETTER = 65;
  int DIGIT = 66;
  int LPAREN = 67;
  int RPAREN = 68;
  int LBRACE = 69;
  int RBRACE = 70;
  int LBRACKET = 71;
  int RBRACKET = 72;
  int SEMICOLON = 73;
  int COMMA = 74;
  int DOT = 75;
  int ASSIGN = 76;
  int GT = 77;
  int GTX = 78;
  int LT = 79;
  int LTX = 80;
  int BANG = 81;
  int TILDE = 82;
  int HOOK = 83;
  int COLON = 84;
  int EQ = 85;
  int LE = 86;
  int LEX = 87;
  int GE = 88;
  int GEX = 89;
  int NE = 90;
  int BOOL_OR = 91;
  int BOOL_ORX = 92;
  int BOOL_AND = 93;
  int BOOL_ANDX = 94;
  int INCR = 95;
  int DECR = 96;
  int PLUS = 97;
  int MINUS = 98;
  int STAR = 99;
  int SLASH = 100;
  int BIT_AND = 101;
  int BIT_ANDX = 102;
  int BIT_OR = 103;
  int BIT_ORX = 104;
  int XOR = 105;
  int MOD = 106;
  int LSHIFT = 107;
  int LSHIFTX = 108;
  int RSIGNEDSHIFT = 109;
  int RSIGNEDSHIFTX = 110;
  int RUNSIGNEDSHIFT = 111;
  int RUNSIGNEDSHIFTX = 112;
  int PLUSASSIGN = 113;
  int MINUSASSIGN = 114;
  int STARASSIGN = 115;
  int SLASHASSIGN = 116;
  int ANDASSIGN = 117;
  int ANDASSIGNX = 118;
  int ORASSIGN = 119;
  int ORASSIGNX = 120;
  int XORASSIGN = 121;
  int MODASSIGN = 122;
  int LSHIFTASSIGN = 123;
  int LSHIFTASSIGNX = 124;
  int RSIGNEDSHIFTASSIGN = 125;
  int RSIGNEDSHIFTASSIGNX = 126;
  int RUNSIGNEDSHIFTASSIGN = 127;
  int RUNSIGNEDSHIFTASSIGNX = 128;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\n\"",
    "<NONPRINTABLE>",
    "<SINGLE_LINE_COMMENT>",
    "<HASH_BANG_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"class\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"transient\"",
    "\"throw\"",
    "\"throws\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<FORMAL_COMMENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"@gt\"",
    "\"<\"",
    "\"@lt\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\"@lteq\"",
    "\">=\"",
    "\"@gteq\"",
    "\"!=\"",
    "\"||\"",
    "\"@or\"",
    "\"&&\"",
    "\"@and\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"@bitwise_and\"",
    "\"|\"",
    "\"@bitwise_or\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"@left_shift\"",
    "\">>\"",
    "\"@right_shift\"",
    "\">>>\"",
    "\"@right_unsigned_shift\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"@and_assign\"",
    "\"|=\"",
    "\"@or_assign\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\"@left_shift_assign\"",
    "\">>=\"",
    "\"@right_shift_assign\"",
    "\">>>=\"",
    "\"@right_unsigned_shift_assign\"",
  };

}
