/* Generated By:JJTree: Do not edit this line. src/bsh/ParserTreeConstants.java */

package bsh;

public interface ParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTMETHODDECLARATION = 1;
  public int JJTIMPORTDECLARATION = 2;
  public int JJTVARIABLEDECLARATOR = 3;
  public int JJTARRAYINITIALIZER = 4;
  public int JJTFORMALPARAMETERS = 5;
  public int JJTFORMALPARAMETER = 6;
  public int JJTTYPE = 7;
  public int JJTRETURNTYPE = 8;
  public int JJTPRIMITIVETYPE = 9;
  public int JJTAMBIGUOUSNAME = 10;
  public int JJTASSIGNMENT = 11;
  public int JJTTERNARYEXPRESSION = 12;
  public int JJTBINARYEXPRESSION = 13;
  public int JJTUNARYEXPRESSION = 14;
  public int JJTCASTEXPRESSION = 15;
  public int JJTPRIMARYEXPRESSION = 16;
  public int JJTMETHODINVOCATION = 17;
  public int JJTPRIMARYSUFFIX = 18;
  public int JJTLITERAL = 19;
  public int JJTARGUMENTS = 20;
  public int JJTALLOCATIONEXPRESSION = 21;
  public int JJTARRAYDIMENSIONS = 22;
  public int JJTBLOCK = 23;
  public int JJTFORMALCOMMENT = 24;
  public int JJTSWITCHSTATEMENT = 25;
  public int JJTSWITCHLABEL = 26;
  public int JJTIFSTATEMENT = 27;
  public int JJTWHILESTATEMENT = 28;
  public int JJTFORSTATEMENT = 29;
  public int JJTENHANCEDFORSTATEMENT = 30;
  public int JJTTYPEDVARIABLEDECLARATION = 31;
  public int JJTSTATEMENTEXPRESSIONLIST = 32;
  public int JJTRETURNSTATEMENT = 33;
  public int JJTTHROWSTATEMENT = 34;
  public int JJTTRYSTATEMENT = 35;


  public String[] jjtNodeName = {
    "void",
    "MethodDeclaration",
    "ImportDeclaration",
    "VariableDeclarator",
    "ArrayInitializer",
    "FormalParameters",
    "FormalParameter",
    "Type",
    "ReturnType",
    "PrimitiveType",
    "AmbiguousName",
    "Assignment",
    "TernaryExpression",
    "BinaryExpression",
    "UnaryExpression",
    "CastExpression",
    "PrimaryExpression",
    "MethodInvocation",
    "PrimarySuffix",
    "Literal",
    "Arguments",
    "AllocationExpression",
    "ArrayDimensions",
    "Block",
    "FormalComment",
    "SwitchStatement",
    "SwitchLabel",
    "IfStatement",
    "WhileStatement",
    "ForStatement",
    "EnhancedForStatement",
    "TypedVariableDeclaration",
    "StatementExpressionList",
    "ReturnStatement",
    "ThrowStatement",
    "TryStatement",
  };
}
