<?xml version='1.0' encoding='UTF-8'?>
<!-- Licensed to the Apache Software Foundation (ASF) under the Apache License, Version 2.0. -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.beanshell</groupId>
    <artifactId>bsh-project</artifactId>
    <version>3.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>bsh-gui</artifactId>
  <name>BeanShell gui</name>
  <properties>
    <checkstyle.skip>false</checkstyle.skip>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.beanshell</groupId>
      <artifactId>bsh</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.beanshell</groupId>
      <artifactId>bsh</artifactId>
      <version>${project.version}</version>
      <type>test-jar</type>
      <classifier>tests</classifier>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
      </resource>
      <resource>
        <directory>..</directory>
        <targetPath>META-INF</targetPath>
        <includes>
          <include>LICENSE</include>
          <include>NOTICE</include>
        </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>biz.aQute.bnd</groupId>
        <artifactId>bnd-maven-plugin</artifactId>
        <configuration>
          <bnd><![CDATA[
Bundle-Version: ${replace;${project.version};-;.}
Bundle-SymbolicName: org.beanshell.bsh-gui
Export-Package: bsh.gui
-includeresource: META-INF/LICENSE=../LICENSE,META-INF/NOTICE=../NOTICE
Private-Package: bsh.gui.internal
Require-Capability: osgi.extender;filter:="(&(osgi.extender=osgi.serviceloader.registrar)(version>=1.0.0)(!(version>=2.0.0)))";resolution:=optional
Provide-Capability: osgi.serviceloader;osgi.serviceloader=bsh.spi.CommandProvider;register:="bsh.gui.internal.GuiCommands";uses:="bsh.spi"
Main-Class: bsh.gui.Console
]]></bnd>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
