/* Generated by: JJTree: Do not edit this line. BSHEnumConstant.java Version 1.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=BSH,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package bsh;

public class BSHEnumConstant extends SimpleNode {
    private static final long serialVersionUID = 1L;
    Modifiers mods = new Modifiers(Modifiers.FIELD);
    {
        mods.setConstant();
        mods.addModifier("enum");
    }
    String name;

    public BSHEnumConstant(int id) { super(id); }

    public Object eval( CallStack callstack, Interpreter interpreter ) throws EvalError {
        NameSpace namespace = callstack.top();
        if ( !getName().equals(""+namespace.classInstance) )
            return Primitive.VOID;

        if (hasArguments(callstack, interpreter))
            This.CONTEXT_ARGS.get().put( namespace.classInstance.toString(), getArguments(callstack, interpreter) );

        for ( int i = 0; i < jjtGetNumChildren(); i++ )
            if ( jjtGetChild(i) instanceof BSHBlock )
                ((BSHBlock) jjtGetChild(i)).eval(callstack, interpreter, true);

        return Primitive.VOID;
    }

    public boolean hasArguments(CallStack callstack, Interpreter interpreter) throws EvalError {
        return null != getArguments(callstack, interpreter);
    }

    Object[] args;
    public Object[] getArguments(CallStack callstack, Interpreter interpreter) throws EvalError {
        if (args == null && jjtGetNumChildren() > 0 && jjtGetChild(0) instanceof BSHArguments) {
            BSHArguments arg = (BSHArguments)jjtGetChild(0);
            args = arg.getArguments(callstack, interpreter);
        }
        return args;
    }

    public Class<?> getType() {
        return Enum.class;
    }

    public String getName( ) {
        return name;
    }

    public String toString() {
        return "EnumConstant: " + mods + ' ' + getType() + ' ' + name;
    }

}
/* JavaCC - OriginalChecksum=6bf5bca59c6d351657103c4ff0e8d054 (do not edit this line) */
