/* Generated by: JJTree: Do not edit this line. Node.java Version 1.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=BSH,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/** Copyright 2018 beanshell.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */
package bsh;

import java.util.ListIterator;

/* All AST nodes must implement this interface.  It provides basic
 * machinery for constructing the parent and child relationships
 * between nodes. */
public interface Node extends bsh.congo.parser.Node, ListIterator<Node> {
    /** Set the name of the source file (or more generally source) of the text
     * from which this node was parsed.
     * @param sourceFile source */
    void setSourceFile(String sourceFile);

    /** Dump the children hierarchy.
     * @param prefix a prefix string */
    void dump(String prefix);

    /** Overloaded toString with prefix used by dump.
     * @param prefix a prefix string
     * @return toString with prefix */
    String toString(String prefix);
}
